version: '3.8'

services:
  api:
    container_name: fastapi
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://dbuser:dbpassword@db:5432/dbname
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ./entrypoint.sh

  db:
    image: postgres:13
    container_name: db-postgres
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
